"""initial schema: sources, content_items, trending_topics, qa_interactions

Revision ID: 6d6e10f2abd1
Revises: 
Create Date: 2026-04-10 00:59:00.027938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d6e10f2abd1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('source_type', sa.Enum('AGENCY', 'RESEARCH_INSTITUTION', 'JOURNAL', 'PREPRINT', 'SCIENCE_MEDIA', 'GENERAL_NEWS', name='sourcetype'), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=True),
    sa.Column('feed_url', sa.Text(), nullable=True),
    sa.Column('institution', sa.Text(), nullable=True),
    sa.Column('credibility_baseline', sa.Integer(), nullable=False),
    sa.Column('region', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_polled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('poll_interval_minutes', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trending_topics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('SPACE', 'QUANTUM', 'THEORETICAL', 'FRONTIER', name='category'), nullable=False),
    sa.Column('trend_score', sa.Float(), nullable=False),
    sa.Column('mention_count_24h', sa.Integer(), nullable=False),
    sa.Column('mention_count_7d', sa.Integer(), nullable=False),
    sa.Column('velocity', sa.Float(), nullable=False),
    sa.Column('related_item_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('original_url', sa.Text(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('author', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('category', sa.Enum('SPACE', 'QUANTUM', 'THEORETICAL', 'FRONTIER', name='category'), nullable=False),
    sa.Column('subcategory', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('summary_quick', sa.Text(), nullable=True),
    sa.Column('summary_expanded', sa.Text(), nullable=True),
    sa.Column('explanation_beginner', sa.Text(), nullable=True),
    sa.Column('explanation_intermediate', sa.Text(), nullable=True),
    sa.Column('explanation_technical', sa.Text(), nullable=True),
    sa.Column('scientific_status', sa.Enum('ESTABLISHED', 'SUPPORTED', 'ACTIVE_RESEARCH', 'SPECULATIVE', 'HIGHLY_SPECULATIVE', 'MEDIA_HYPE', name='scientificstatus'), nullable=True),
    sa.Column('credibility_score', sa.Integer(), nullable=True),
    sa.Column('credibility_explanation', sa.Text(), nullable=True),
    sa.Column('trend_score', sa.Float(), nullable=True),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('cleaned_content', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('original_url')
    )
    op.create_table('qa_interactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['content_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Indexes per spec Section 6.2
    op.create_index('ix_content_items_category', 'content_items', ['category'])
    op.create_index('ix_content_items_published_at', 'content_items', [sa.text('published_at DESC')])
    op.create_index('ix_content_items_credibility_score', 'content_items', [sa.text('credibility_score DESC')])
    op.create_index('ix_content_items_scientific_status', 'content_items', ['scientific_status'])
    op.create_index('ix_content_items_tags', 'content_items', ['tags'], postgresql_using='gin')
    op.create_index('ix_trending_topics_category_score', 'trending_topics', ['category', sa.text('trend_score DESC')])
    op.create_index('ix_sources_active_type', 'sources', ['is_active', 'source_type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qa_interactions')
    op.drop_table('content_items')
    op.drop_table('trending_topics')
    op.drop_table('sources')
    # ### end Alembic commands ###
